name: Daily Build
on:
  push:
    branches:
      - main
    paths:
      - 'metrics/'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run build script
      run: python src/library.py

    - name: Set git user
      run: |
        git config --global user.name "massyn"
        git config --global user.email "phil@massyn.net"

    - name: Commit changes
      run: |
        git add docs/*.md
        git commit -m "Automated commit: Update README.md"

    - name: Push changes
      run: |
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}